const userArray = [
  {
    name: "Asmir Khan",
    email: "asmir@thirantech.com",
    role: "Developer",
    number: "1234567890",
    experience: 5,
    gender: "male",
    password: "pass1234",
    isLogged: false,
    projects: [],
  },
  {
    name: "Parvatha",
    email: "parvatha@thirantech.com",
    role: "Designer",
    number: "9876543210",
    experience: 3,
    gender: "female",
    password: "pass1234",
    isLogged: false,
    projects: [],
  },
  {
    name: "Madhu",
    email: "madhu@thirantech.com",
    role: "Manager",
    number: "5555555555",
    experience: 8,
    gender: "female",
    password: "pass1234",
    isLogged: false,
    projects: [],
  },
  {
    name: "Michael",
    email: "michael@thirantech.com",
    role: "Tester",
    number: "7777777777",
    experience: 2,
    gender: "male",
    password: "pass1234",
    isLogged: false,
    projects: [],
  },
  {
    name: "Karthick",
    email: "karthick@thirantech.com",
    role: "Engineer",
    number: "9999999999",
    experience: 6,
    gender: "male",
    password: "pass1234",
    isLogged: false,
    projects: [],
  },
  {
    name: "Balaji",
    email: "balaji@thirantech.com",
    role: "Product Manager",
    number: "1111111111",
    experience: 4,
    gender: "male",
    password: "pass1234",
    isLogged: false,
    projects: [],
  },
  {
    name: "Devipriya",
    email: "devipriya@thirantech.com",
    role: "QA Analyst",
    number: "2222222222",
    experience: 3,
    gender: "female",
    password: "pass1234",
    isLogged: false,
    projects: [],
  },
  {
    name: "Ramya",
    email: "ramya@thirantech.com",
    role: "Marketing Specialist",
    number: "3333333333",
    experience: 2,
    gender: "female",
    password: "pass1234",
    isLogged: false,
    projects: [],
  },
  {
    name: "Henry",
    email: "henry@thirantech.com",
    role: "Data Analyst",
    number: "4444444444",
    experience: 4,
    gender: "male",
    password: "pass1234",
    isLogged: false,
    projects: [],
  },
  {
    name: "Chris",
    email: "Chris@thirantech.com",
    role: "Sales Representative",
    number: "6666666666",
    experience: 1,
    gender: "male",
    password: "pass1234",
    isLogged: false,
    projects: [],
  },
];

export default userArray;
