const dummyProjects = [
  {
    name: "E-commerce Website",
    description: "Develop an e-commerce website with online shopping features.",
    startDate: "2023-01-01",
    endDate: "2023-02-01",
    priority: "High",
    techStack: "React, Node.js",
    selectedUsers: [],
  },
  {
    name: "Social Media App",
    description:
      "Create a social media platform for users to connect and share content.",
    startDate: "2023-03-01",
    endDate: "2023-04-01",
    priority: "Medium",
    techStack: "Angular, Express",
    selectedUsers: [],
  },
  {
    name: "Inventory Management System",
    description: "Build a system to track and manage inventory for businesses.",
    startDate: "2023-05-01",
    endDate: "2023-06-01",
    priority: "Low",
    techStack: "Vue.js, Django",
    selectedUsers: [],
  },
  {
    name: "Online Learning Platform",
    description:
      "Design an online platform for educational courses and tutorials.",
    startDate: "2023-07-01",
    endDate: "2023-08-01",
    priority: "High",
    techStack: "React, Ruby on Rails",
    selectedUsers: [],
  },
  {
    name: "Health and Fitness App",
    description:
      "Develop a mobile app to help users with their fitness goals and health tracking.",
    startDate: "2023-09-01",
    endDate: "2023-10-01",
    priority: "Medium",
    techStack: "Angular, Node.js",
    selectedUsers: [],
  },
  {
    name: "Project 6",
    description: "Description of Project 6",
    startDate: "2023-11-01",
    endDate: "2023-12-01",
    priority: "Low",
    techStack: "Vue.js, Express",
    selectedUsers: [],
  },
  {
    name: "Project 7",
    description: "Description of Project 7",
    startDate: "2024-01-01",
    endDate: "2024-02-01",
    priority: "High",
    techStack: "React, Django",
    selectedUsers: [],
  },
  {
    name: "Project 8",
    description: "Description of Project 8",
    startDate: "2024-03-01",
    endDate: "2024-04-01",
    priority: "Medium",
    techStack: "Angular, Ruby on Rails",
    selectedUsers: [],
  },
  {
    name: "Project 9",
    description: "Description of Project 9",
    startDate: "2024-05-01",
    endDate: "2024-06-01",
    priority: "Low",
    techStack: "Vue.js, Node.js",
    selectedUsers: [],
  },
  {
    name: "Project 10",
    description: "Description of Project 10",
    startDate: "2024-07-01",
    endDate: "2024-08-01",
    priority: "High",
    techStack: "React, Express",
    selectedUsers: [],
  },
];

export default dummyProjects;
