const projectArray = [
  {
    name: "John Doe",
    email: "john@example.com",
    role: "Developer",
    number: "1234567890",
    experience: 5,
    gender: "male",
  },
  {
    name: "Jane Smith",
    email: "jane@example.com",
    role: "Designer",
    number: "9876543210",
    experience: 3,
    gender: "female",
  },
  {
    name: "Bob Johnson",
    email: "bob@example.com",
    role: "Manager",
    number: "5555555555",
    experience: 8,
    gender: "male",
  },
  {
    name: "Alice Brown",
    email: "alice@example.com",
    role: "Tester",
    number: "7777777777",
    experience: 2,
    gender: "female",
  },
  {
    name: "Mike Wilson",
    email: "mike@example.com",
    role: "Engineer",
    number: "9999999999",
    experience: 6,
    gender: "male",
  },
  {
    name: "Emily Davis",
    email: "emily@example.com",
    role: "Product Manager",
    number: "1111111111",
    experience: 4,
    gender: "female",
  },
  {
    name: "Tom Adams",
    email: "tom@example.com",
    role: "QA Analyst",
    number: "2222222222",
    experience: 3,
    gender: "male",
  },
  {
    name: "Sarah Clark",
    email: "sarah@example.com",
    role: "Marketing Specialist",
    number: "3333333333",
    experience: 2,
    gender: "female",
  },
  {
    name: "Chris Lee",
    email: "chris@example.com",
    role: "Data Analyst",
    number: "4444444444",
    experience: 4,
    gender: "male",
  },
  {
    name: "Linda Turner",
    email: "linda@example.com",
    role: "Sales Representative",
    number: "6666666666",
    experience: 1,
    gender: "female",
  },
];

export default projectArray;
