const dummyProjects = [
  {
    id: 1,
    name: "Project 1",
    description: "Description of Project 1",
    startDate: "2023-01-01",
    endDate: "2023-02-01",
    priority: "High",
    techStack: "React, Node.js",
    selectedUsers: [],
  },
  {
    id: 2,
    name: "Project 2",
    description: "Description of Project 2",
    startDate: "2023-03-01",
    endDate: "2023-04-01",
    priority: "Medium",
    techStack: "Angular, Express",
    selectedUsers: [],
  },
  {
    id: 3,
    name: "Project 3",
    description: "Description of Project 3",
    startDate: "2023-05-01",
    endDate: "2023-06-01",
    priority: "Low",
    techStack: "Vue.js, Django",
    selectedUsers: [],
  },
  {
    id: 4,
    name: "Project 4",
    description: "Description of Project 4",
    startDate: "2023-07-01",
    endDate: "2023-08-01",
    priority: "High",
    techStack: "React, Ruby on Rails",
    selectedUsers: [],
  },
  {
    id: 5,
    name: "Project 5",
    description: "Description of Project 5",
    startDate: "2023-09-01",
    endDate: "2023-10-01",
    priority: "Medium",
    techStack: "Angular, Node.js",
    selectedUsers: [],
  },
  {
    id: 6,
    name: "Project 6",
    description: "Description of Project 6",
    startDate: "2023-11-01",
    endDate: "2023-12-01",
    priority: "Low",
    techStack: "Vue.js, Express",
    selectedUsers: [],
  },
  {
    id: 7,
    name: "Project 7",
    description: "Description of Project 7",
    startDate: "2024-01-01",
    endDate: "2024-02-01",
    priority: "High",
    techStack: "React, Django",
    selectedUsers: [],
  },
  {
    id: 8,
    name: "Project 8",
    description: "Description of Project 8",
    startDate: "2024-03-01",
    endDate: "2024-04-01",
    priority: "Medium",
    techStack: "Angular, Ruby on Rails",
    selectedUsers: [],
  },
  {
    id: 9,
    name: "Project 9",
    description: "Description of Project 9",
    startDate: "2024-05-01",
    endDate: "2024-06-01",
    priority: "Low",
    techStack: "Vue.js, Node.js",
    selectedUsers: [],
  },
  {
    id: 10,
    name: "Project 10",
    description: "Description of Project 10",
    startDate: "2024-07-01",
    endDate: "2024-08-01",
    priority: "High",
    techStack: "React, Express",
    selectedUsers: [],
  },
];

export default dummyProjects;
